# Generated by Django 5.2.17 on 2026-09-24 03:15

import cuentas.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="correo"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Como aparece en el sistema: Lic. Nombre Apellido",
                        max_length=120,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("aprueba", "Socio director (aprueba)"),
                            ("revisa", "Abogado senior (revisa)"),
                            ("elabora", "Abogado (elabora)"),
                            ("auxiliar", "Auxiliar jurídico"),
                        ],
                        default="elabora",
                        max_length=20,
                        verbose_name="rol",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Puede administrar el equipo y la configuración",
                        verbose_name="administrador",
                    ),
                ),
                ("fecha_alta", models.DateTimeField(default=django.utils.timezone.now)),
                ("intentos_fallidos", models.PositiveSmallIntegerField(default=0)),
                ("bloqueado_hasta", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "ordering": ["nombre"],
            },
            managers=[
                ("objects", cuentas.models.UsuarioManager()),
            ],
        ),
    ]
