from django.urls import path

from . import views

urlpatterns = [
    path("litigios/", views.tablero, name="tablero"),
    path("expedientes/", views.expedientes, name="expedientes"),
    path("expedientes/<slug:filtro>/", views.expedientes, name="expedientes_filtro"),
    path("expediente/nuevo/", views.expediente_nuevo, name="expediente_nuevo"),
    path("expediente/<int:pk>/", views.expediente, name="expediente"),
    path("expediente/<int:pk>/editar/", views.expediente_editar, name="expediente_editar"),
    path("expediente/<int:pk>/eliminar/", views.expediente_eliminar, name="expediente_eliminar"),
    path("expediente/<int:pk>/etapa/", views.expediente_etapa, name="expediente_etapa"),
    path("expediente/<int:pk>/estado/", views.expediente_estado, name="expediente_estado"),
    path("expediente/<int:pk>/informe/", views.expediente_informe, name="expediente_informe"),
    path("expediente/<int:pk>/accion/nueva/", views.accion_nueva, name="accion_nueva"),
    path("expediente/<int:pk>/documento/nuevo/", views.documento_nuevo, name="documento_nuevo"),
    path("expediente/<int:pk>/bitacora/nueva/", views.bitacora_nueva, name="bitacora_nueva"),
    path("expediente/<int:pk>/recurso/nuevo/", views.recurso_nuevo, name="recurso_nuevo_exp"),
    path("accion/<int:pk>/editar/", views.accion_editar, name="accion_editar"),
    path("accion/<int:pk>/eliminar/", views.accion_eliminar, name="accion_eliminar"),
    path("accion/<int:pk>/avanzar/", views.accion_avanzar, name="accion_avanzar"),
    path("accion/<int:pk>/terminar/", views.accion_terminar, name="accion_terminar"),
    path("acuerdos/", views.acuerdos, name="acuerdos"),
    path("acuerdo/nuevo/", views.acuerdo_nuevo, name="acuerdo_nuevo"),
    path("documento/<int:pk>/descargar/", views.documento_descargar, name="documento_descargar"),
    path("documento/<int:pk>/adjuntar/", views.documento_adjuntar, name="documento_adjuntar"),
    path("documento/<int:pk>/quitar/", views.documento_quitar, name="documento_quitar"),
    path("recursos/", views.recursos, name="recursos"),
    path("recurso/nuevo/", views.recurso_nuevo, name="recurso_nuevo"),
    path("recurso/<int:pk>/editar/", views.recurso_editar, name="recurso_editar"),
    path("recurso/<int:pk>/avanzar/", views.recurso_etapa, {"direccion": "avanzar"}, name="recurso_avanzar"),
    path("recurso/<int:pk>/regresar/", views.recurso_etapa, {"direccion": "regresar"}, name="recurso_regresar"),
    path("recurso/<int:pk>/resolver/", views.recurso_resolver, name="recurso_resolver"),
    path("recurso/<int:pk>/reabrir/", views.recurso_reabrir, name="recurso_reabrir"),
    path("recurso/<int:pk>/eliminar/", views.recurso_eliminar, name="recurso_eliminar"),
    path("calendario/", views.calendario, name="calendario"),
    path("equipo/", views.equipo, name="equipo"),
    path("plazo/calcular/", views.calcular_plazo, name="calcular_plazo"),
    path("corporativo/", views.corporativo, name="corporativo"),
]
