# Generated by Django 5.2.17 on 2026-09-24 03:15

import django.db.models.deletion
import django.db.models.manager
import litigios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eliminado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "razon",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="razón social o nombre",
                    ),
                ),
                (
                    "rfc",
                    models.CharField(blank=True, max_length=13, verbose_name="RFC"),
                ),
                (
                    "representante",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="representante legal"
                    ),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="contacto"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "eliminado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["razon"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eliminado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=60, verbose_name="número de expediente"
                    ),
                ),
                ("anio", models.CharField(max_length=4, verbose_name="año")),
                ("juzgado", models.CharField(max_length=200, verbose_name="juzgado")),
                ("materia", models.CharField(max_length=30, verbose_name="materia")),
                (
                    "tipo",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="tipo de asunto"
                    ),
                ),
                (
                    "caracter",
                    models.CharField(
                        default="Actor",
                        max_length=40,
                        verbose_name="carácter del cliente",
                    ),
                ),
                (
                    "contraparte",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="contraparte"
                    ),
                ),
                (
                    "etapa",
                    models.CharField(max_length=60, verbose_name="etapa procesal"),
                ),
                (
                    "audiencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="próxima audiencia"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("sentencia", "En espera de sentencia"),
                            ("terminado", "Terminado"),
                        ],
                        default="activo",
                        max_length=12,
                    ),
                ),
                (
                    "cuantia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="cuantía (MXN)",
                    ),
                ),
                ("esperando_auto", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedientes",
                        to="litigios.cliente",
                    ),
                ),
                (
                    "eliminado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="abogado responsable",
                    ),
                ),
            ],
            options={
                "ordering": ["creado_en", "id"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EntradaBitacora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("texto", models.TextField()),
                ("quien_nombre", models.CharField(max_length=120)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "quien",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bitacora",
                        to="litigios.expediente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eliminado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=250, verbose_name="nombre de la constancia"
                    ),
                ),
                ("fecha", models.DateField()),
                ("quien_nombre", models.CharField(blank=True, max_length=120)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, max_length=300, upload_to=litigios.models.ruta_pdf
                    ),
                ),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("tamano", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "eliminado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quien",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="litigios.expediente",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "id"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Acuerdo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha de publicación")),
                ("sintesis", models.TextField(verbose_name="qué se acordó")),
                (
                    "accion",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="acción a seguir"
                    ),
                ),
                (
                    "plazo",
                    models.DateField(
                        blank=True, null=True, verbose_name="plazo que corre"
                    ),
                ),
                ("registrado_por_nombre", models.CharField(blank=True, max_length=120)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acuerdos",
                        to="litigios.expediente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eliminado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "tipo",
                    models.CharField(max_length=40, verbose_name="tipo de recurso"),
                ),
                (
                    "promovente",
                    models.CharField(
                        default="Nosotros",
                        max_length=20,
                        verbose_name="quién lo promueve",
                    ),
                ),
                (
                    "acto_impugnado",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="acto o resolución impugnada",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="toca o número de expediente",
                    ),
                ),
                (
                    "organo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="órgano que lo resuelve",
                    ),
                ),
                (
                    "fecha_interposicion",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de interposición"
                    ),
                ),
                ("etapa", models.CharField(max_length=80, verbose_name="etapa actual")),
                (
                    "suspension",
                    models.CharField(
                        default="No aplica", max_length=40, verbose_name="suspensión"
                    ),
                ),
                ("estado", models.CharField(default="tramite", max_length=10)),
                ("resultado", models.CharField(blank=True, max_length=40)),
                ("fecha_resolucion", models.DateField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "eliminado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recursos",
                        to="litigios.expediente",
                    ),
                ),
            ],
            options={
                "ordering": ["creado_en", "id"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Accion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eliminado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=250, verbose_name="documento, promoción o acto"
                    ),
                ),
                ("tipo", models.CharField(default="Promoción", max_length=30)),
                (
                    "plazo",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="fecha límite o plazo judicial",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("elaboracion", "En elaboración"),
                            ("revision", "En revisión"),
                            ("aprobada", "Aprobada"),
                            ("terminada", "Terminada"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("acuse", models.CharField(blank=True, max_length=200)),
                ("terminada_el", models.DateField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "aprueba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eliminado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsable (elabora)",
                    ),
                ),
                (
                    "revisa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acciones",
                        to="litigios.expediente",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones",
                        to="litigios.recurso",
                    ),
                ),
            ],
            options={
                "ordering": ["creado_en", "id"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificacionEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=20)),
                ("plazo", models.DateField(null=True)),
                ("enviada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "accion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notificaciones",
                        to="litigios.accion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("accion", "tipo", "plazo"), name="notificacion_unica"
                    )
                ],
            },
        ),
    ]
